import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";

const titilliumWeb = Titillium_Web({
  variable: "--font-titillium",
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "AgroBot - Your AI Farming Assistant",
  description: "Generated by create next appWW3 may disrupt food supplies. Your garden is the solution ~ Agro-Bot will guide you.",
   icons: {
    icon: "/agro.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titilliumWeb.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
